base: develop
mode: auto
silent: false
branchName: "${issue.number}-${issue.title}"
autoCloseIssue: true
convertTitleToKebabCase: true
branches:
  - label: "enhancement"
    name: "feature/${branchName}"
  - label: "bug"
    name: "bugfix/${branchName}"
  - label: "documentation"
    name: "docs/${branchName}"
  - label: "*"
    name: "task/${branchName}"
