name: Task Template
description: Basic task template
body:
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      value: "- [ ] "
  - type: textarea
    id: out-of-scope
    attributes:
      label: "Out of Scope"
      value: ""
