name: Create Issue Branch
on:
  issues:
    types: [opened]
    
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-file: .github/issue-branch.yml
          branch-name: "${issue.number}-${issue.title}"
          auto-close: true
          kebab-case: true
